dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD
  - VERSION=3.3.0
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=2.0.0

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Expose the database and Drupal site URLs to PHPUnit.
  - export SIMPLETEST_DB=sqlite://localhost/db.sqlite
  - export SIMPLETEST_BASE_URL=http://127.0.0.1:8080
  # Silence deprecation notices to prevent test failures we can't fix.
  - export SYMFONY_DEPRECATIONS_HELPER=weak

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - pecl channel-update pecl.php.net
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the code base. There is no lock file in the repo, so dependencies will
  # always be renegotiated.
  - composer install
  # Install on top of Minimal for testing, then export config and reinstall
  # from that to ensure that the exported config is coherent.
  - lightning install "sqlite\://db.sqlite" minimal "http://127.0.0.1:8080" --from-config --no-dev
  # Restore database fixture from the version we're testing and run database and
  # and Lightning config updates.
  - lightning update $VERSION

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

script:
  - composer validate composer.json --no-check-all --ansi --no-interaction
  - phpunit --configuration ./docroot/core --group lightning,profiles
  - behat

after_failure:
  - cd docroot
  - drush watchdog:show --count=100 --severity=Error --extended
