sudo: true
language: php
dist: trusty
php:
- 7.1
matrix:
  fast_finish: true
env:
  global:
  - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
  - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
  - BUILD_DIR=$TRAVIS_BUILD_DIR
jdk:
- oraclejdk8
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - ".rules"
addons:
  ssh_known_hosts:
  - svn-5767.devcloud.hosting.acquia.com
  chrome: stable
notifications: 
before_install:
- openssl aes-256-cbc -K $encrypted_c0e917d90fe7_key -iv $encrypted_c0e917d90fe7_iv
  -in jktravis.enc -out ~\/.ssh/jktravis -d
- '$(npm bin)/set-up-ssh --key "$encrypted_c0e917d90fe7_key" -iv "$encrypted_c0e917d90fe7_iv"
  --path-encrypted-key "jktravis.enc"

'
- phpenv config-rm xdebug.ini
- composer self-update
- composer validate --no-check-all --ansi
- composer install
- source ${BLT_DIR}/scripts/travis/exit_early
install:
- source ${BLT_DIR}/scripts/travis/setup_environment
- source ${BLT_DIR}/scripts/travis/setup_project
script:
- source ${BLT_DIR}/scripts/travis/run_tests
deploy:
- provider: script
  script: "${BLT_DIR}/scripts/travis/deploy_branch"
  skip_cleanup: true
  on:
    branch: develop
    php: 7.1
- provider: script
  script: "${BLT_DIR}/scripts/travis/deploy_branch"
  skip_cleanup: true
  on:
    branch: master
    php: 7.1
- provider: script
  script: "${BLT_DIR}/scripts/travis/deploy_tag"
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
