sudo: true
language: php
dist: trusty

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR
    - secure: X/J2vntLmc1eWBBHh0KLvLUyX45WzCOIurWwsMteOQd3BTCwkrHiCs5L/wbagpMgES1HUsc7en26QPu+v6Al72trNcgaAAM7IxULungB8GxmA4NOxhaNw2YMiGnA5GmIHFevIRY/J8YBbtU5q9gZz2rLuzXKsOeB8cm9rArtlQNkctTkZ/gpbx+VmlszKKeCKNLziPyCDxT/bT7hTNoaohD4XR1IJmQLlqNN+Rq2u7uyiXcyBHZzQSHDxjexo7q5hUDsM02Ln6Y34oW094sqxwFV/C9HCywIwxCB9unts03CQq8anGOWq4Sf3dXNvAhVtBqFmpGrwrTttw6ynJD7vNDOLUuoADe0FWW3arR02yIw48UF1qwE1wDOGcGA/QtAoDwJXN00nRCzyUo6gCEEVBq4MRzlp20dtRQAdF26cQIw9ibj2qkyl7xjtsu/niA/fNU1DtU2lz7sg+9nRi4HLzK6J/H2dv3IcJV0/1FfZtdhulYiR7+koUzUgJqNwcHEM0qgfGD9OA1o7w+2bJ7irYCWuC9hyiKzlw5Q0VKvNqwCLSUTWQqPLOjp/PkrWUFGTtim95UDaFPtd5Wn7bumkb7beGC6pGJ4azpcBmr3jx7p5aJLgUZRx7rKBo02FhY9yuXdycLxzbQOxLMZdbSGxxflrLC25OD6Lgq7P+3nseg=

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - ".rules"
  # Cache front end dependencies to dramatically improve build time.
  # - "docroot/themes/custom/mytheme/node_modules"
  # - "docroot/themes/custom/mytheme/bower_components"

addons:
  ssh_known_hosts:
   - svn-5767.devcloud.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
notifications:
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'

before_install:
# Disable xdebug.
  - openssl aes-256-cbc -K $encrypted_c0e917d90fe7_key -iv $encrypted_c0e917d90fe7_iv -in jktravis.enc -out $HOME/.ssh/jktravis -d
  - chmod 600 $HOME/.ssh/jktravis
  - eval `ssh-agent -s`
  - ssh-add $HOME/.ssh/jktravis
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  - source ${BLT_DIR}/scripts/travis/run_tests

# The version below MUST match the php version indicated at the top of this file, otherwise the artifact won't build.
deploy:
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.1
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.1
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 7.1
